FROM golang:1.26-alpine
RUN apk add --no-cache ca-certificates git
ARG TARGETPLATFORM
COPY ${TARGETPLATFORM}/toga /usr/local/bin/toga
ENV GOMODCACHE=/go/pkg/mod
ENV TOGA_MODCACHE_CLEANUP_INTERVAL=672h
EXPOSE 6060
ENTRYPOINT ["toga"]
