name: ci

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Build
        run: go build ./...

      - name: Test
        run: go test -race ./...

      - name: Vet
        run: go vet ./...

      - name: Staticcheck
        uses: dominikh/staticcheck-action@v1
        with:
          version: latest
